application: apodemail
version: sendgrid
runtime: python27
api_version: 1
threadsafe: true

derived_file_type:
- python_precompiled

libraries:
- name: django
  version: latest

handlers:
- url: /dailyemail
  script: main.app
  login: admin

- url: /usercount
  script: main.app
  login: admin

- url: /email-queue
  script: main.app
  login: admin

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /public/style.css
  static_files: public/style.css
  upload: public/style.css

- url: /.*
  script: main.app
