application: apodemail-hrd
version: stable
runtime: python27
api_version: 1
threadsafe: true

derived_file_type:
- python_precompiled

libraries:
- name: django
  version: latest

builtins:
- appstats: on

handlers:
- url: /dailyemail/(.*)
  script: main.app
  login: admin

- url: /usercount
  script: main.app
  login: admin

- url: /email-queue
  script: main.app
  login: admin

- url: /favicon.ico
  static_files: public/img/favicon.ico
  upload: public/img/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /img/(.*)
  static_files: public/img/\1
  upload: public/img/(.*)

- url: /signup
  script: signup.app

- url: /admin/delete/user
  script: signup.app
  login: admin

- url: /adhocemail
  script: main.app
  login: admin

- url: /.*
  script: main.app
